export enum routes {
    HOME = '/accueil',
    HOMEBLANK = '/',
    DOMAINES = '/app/domaines',
    ADMISSION = '/app/admission',
    RESEARCH = '/app/research',
    ACTIVITIES = '/app/activities',
    CENTRES = '/app/centres',
    ARTICLES = '/app/articles',
    ARTICLESDETAILS = '/articles',
    CONTACTS = '/app/contacts',
    FAQ = '/app/faq',
    PROFILE = '/app/profile',

    ABOUT = '/about',
    COMPLAINTS = 'https://plaintes.ulpgl.net',
    TFE = 'https://sgt.ulpgl.net',
    LIBRARY = 'https://bibliotheque.ulpgl.net',
    RESSOURCES = '/app/ressources',
    KAUTA = '/app/ecole-primaire-kauta',
    METANOIA = '/app/ecole-secondaire-metanoia',
    KAUTA_MATERNEL = '/app/ecole-maternelle-kauta',
    ANCIENS = '/app/anciens-de-lulpgl',
}